browser = "chrome"
url = "https://demo.nopcommerce.com/"
user_gender = "Female"
user_first_name = "Shashini"
user_last_name = "Amasha"
user_date_of_birth_day = "17"
user_date_of_birth_month = "1"
user_date_of_birth_year = "1997"
user_email = "testterr@test.com"
user_company = "Test"
user_newsletter = "true"
user_password = "Test@123"
user_confirm_password = "Test@123"


